# Uncomment this line to define a global platform for your project
# platform :ios, '9.0'

target 'Mapka3' do
  # Uncomment this line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for NearBy


  pod 'React', path: '../node_modules/react-native', :subspecs => [
  'Core',
  'RCTActionSheet',
  'RCTGeolocation',
  'RCTImage',
  'RCTLinkingIOS',
  'RCTNetwork',
  'RCTSettings',
  'RCTText',
  'RCTVibration',
  'RCTWebSocket'
  ]

  pod 'GoogleMaps'



end
source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '8.0'
use_frameworks!

